# Generated by Django 3.1.1 on 2020-09-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='AccountIndicator',
            field=models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], default='D', max_length=1),
        ),
    ]
