# Generated by Django 3.1.1 on 2020-09-20 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_balancesheet_accountindicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('AccountCode', models.CharField(max_length=500, primary_key=True, serialize=False, unique=True)),
                ('AccountName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CostCenters',
            fields=[
                ('CostCenterCode', models.CharField(max_length=500, primary_key=True, serialize=False, unique=True)),
                ('CostCenterName', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='accountingchart',
            name='AccountName',
        ),
        migrations.RemoveField(
            model_name='accountingchart',
            name='CostCenterName',
        ),
        migrations.RemoveField(
            model_name='balancesheet',
            name='AccountName',
        ),
        migrations.RemoveField(
            model_name='balancesheet',
            name='CostCenterName',
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='CompanyCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='CNPJ',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='CompanyCode',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='accountingchart',
            name='AccountCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.accounts'),
        ),
        migrations.AlterField(
            model_name='accountingchart',
            name='CostCenterCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.costcenters'),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='AccountCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.accounts'),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='CostCenterCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.costcenters'),
        ),
    ]
