# Generated by Django 3.1.1 on 2020-09-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockM001',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlockName', models.CharField(default='M001', max_length=4)),
                ('Informed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BlockM010',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlockName', models.CharField(default='M010', max_length=4)),
                ('BAccountCode', models.CharField(max_length=500)),
                ('BAccountDesc', models.CharField(max_length=500)),
                ('AccountCreatedDate', models.DateField(max_length=8)),
                ('DefaultTableCode', models.CharField(max_length=6)),
                ('LimitDate', models.DateField(max_length=8)),
                ('TaxCode', models.CharField(max_length=1)),
                ('InitialBalance', models.DecimalField(decimal_places=2, max_digits=12, max_length=19)),
                ('InitialBalanceInd', models.CharField(max_length=1)),
                ('CNPJEspSituation', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='BlockM030',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlockName', models.CharField(default='M030', max_length=4)),
                ('InitialDate', models.DateField(max_length=8)),
                ('FinalDate', models.DateField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='BlockM300',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlockName', models.CharField(default='M300', max_length=4)),
                ('LalurCode', models.IntegerField()),
                ('LalurName', models.CharField(max_length=500)),
                ('AdjustmentType', models.CharField(max_length=1)),
                ('RelationType', models.CharField(max_length=1)),
                ('Value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Comments', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='BlockM305',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlockName', models.CharField(default='M305', max_length=4)),
                ('BAccountCode', models.CharField(max_length=500)),
                ('Value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ValueInd', models.CharField(max_length=1)),
                ('LalurCode', models.IntegerField()),
                ('LalurName', models.CharField(max_length=500)),
                ('AccountCode', models.CharField(max_length=500)),
                ('CostCenterCode', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='BlockM310',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlockName', models.CharField(default='M310', max_length=4)),
                ('AccountCode', models.CharField(max_length=500)),
                ('CostCenterCode', models.CharField(max_length=500)),
                ('Value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ValueInd', models.CharField(max_length=1)),
            ],
        ),
    ]
