# Generated by Django 3.1.1 on 2020-09-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockm001',
            name='BlockName',
            field=models.CharField(default='M001', editable=False, max_length=4),
        ),
        migrations.AlterField(
            model_name='blockm010',
            name='BlockName',
            field=models.CharField(default='M010', editable=False, max_length=4),
        ),
        migrations.AlterField(
            model_name='blockm010',
            name='InitialBalanceInd',
            field=models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], max_length=1),
        ),
        migrations.AlterField(
            model_name='blockm010',
            name='LimitDate',
            field=models.DateField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='blockm010',
            name='TaxCode',
            field=models.CharField(choices=[('I', 'IR'), ('C', 'CSLL')], max_length=1),
        ),
        migrations.AlterField(
            model_name='blockm030',
            name='BlockName',
            field=models.CharField(default='M030', editable=False, max_length=4),
        ),
        migrations.AlterField(
            model_name='blockm300',
            name='AdjustmentType',
            field=models.CharField(choices=[('A', 'Adição'), ('E', 'Exclusão'), ('P', 'Compensação de Prejuízo'), ('L', 'Lucro')], max_length=1),
        ),
        migrations.AlterField(
            model_name='blockm300',
            name='BlockName',
            field=models.CharField(default='M300', editable=False, max_length=4),
        ),
        migrations.AlterField(
            model_name='blockm300',
            name='RelationType',
            field=models.CharField(choices=[('1', 'Com conta da parte B'), ('2', 'Com conta contábil'), ('3', 'Com conta da parte B e conta contábil'), ('4', 'Sem relacionamento')], max_length=1),
        ),
        migrations.AlterField(
            model_name='blockm305',
            name='AccountCode',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='blockm305',
            name='BlockName',
            field=models.CharField(default='M305', editable=False, max_length=4),
        ),
        migrations.AlterField(
            model_name='blockm305',
            name='CostCenterCode',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='blockm305',
            name='ValueInd',
            field=models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], max_length=1),
        ),
        migrations.AlterField(
            model_name='blockm310',
            name='BlockName',
            field=models.CharField(default='M310', editable=False, max_length=4),
        ),
        migrations.AlterField(
            model_name='blockm310',
            name='ValueInd',
            field=models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], max_length=1),
        ),
    ]
