# Generated by Django 3.1.1 on 2020-09-20 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20200920_1703'),
        ('blockM', '0002_auto_20200920_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='BAccounts',
            fields=[
                ('BAccountCode', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('BAccountDesc', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Lalur',
            fields=[
                ('LalurCode', models.IntegerField(primary_key=True, serialize=False)),
                ('LalurName', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='blockm010',
            name='BAccountDesc',
        ),
        migrations.RemoveField(
            model_name='blockm300',
            name='LalurName',
        ),
        migrations.AlterField(
            model_name='blockm305',
            name='AccountCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.accounts'),
        ),
        migrations.AlterField(
            model_name='blockm305',
            name='CostCenterCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.costcenters'),
        ),
        migrations.AlterField(
            model_name='blockm310',
            name='AccountCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.accounts'),
        ),
        migrations.AlterField(
            model_name='blockm310',
            name='CostCenterCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.costcenters'),
        ),
        migrations.AlterField(
            model_name='blockm010',
            name='BAccountCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockM.baccounts'),
        ),
        migrations.AlterField(
            model_name='blockm300',
            name='LalurCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockM.lalur'),
        ),
        migrations.AlterField(
            model_name='blockm305',
            name='BAccountCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockM.baccounts'),
        ),
        migrations.AlterField(
            model_name='blockm305',
            name='LalurCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockM.lalur'),
        ),
    ]
